#!groovy
@Library('jenkins-pipeline-lib') _

pipeline
{
  agent any
  environment
  {
    GIT_CHANGE_LOG = gitChangeLog(currentBuild.changeSets)
  }
  stages
  {
    stage('Setup')
    {
      steps
      {
        sh 'make clean'
      }
    }
    stage('Build')
    {
      steps
      {
        sh 'make'
      }
    }
  }
  post
  {
    always
    {
      sendNotifications(currentBuild.currentResult)
    }
  }
}
